OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a POKéMON battle ends, all used\n"
	.string "items except berries are restored.\p"
	.string "Even when you switch it away with\n"
	.string "TRICK, you'll get it back!\p"
	.string "Don't worry, everyone here is nice,\n"
	.string "they will return your items if they\l"
	.string "stole them.\p"
	.string "They're so stupid!\p"
	.string "I bought this house with stolen items\n"
	.string "alone!$"

