#ifndef GUARD_STARTER_CHOOSE_H
#define GUARD_STARTER_CHOOSE_H

#define STARTER_MON_COUNT   3
static const u16 sStarterMon2[64][STARTER_MON_COUNT] = {
        {SPECIES_BULBASAUR, SPECIES_SQUIRTLE, SPECIES_CHARMANDER},      // 0
        {SPECIES_CHIKORITA, SPECIES_TOTODILE, SPECIES_CYNDAQUIL},       // 1
        {SPECIES_BULBASAUR, SPECIES_AZURILL, SPECIES_DRATINI},          // 2
        {SPECIES_CHARMANDER, SPECIES_BUDEW, SPECIES_GEODUDE_ALOLAN},    // 3
        {SPECIES_SQUIRTLE, SPECIES_RHYHORN, SPECIES_MAREEP},            // 4
        {SPECIES_CATERPIE, SPECIES_SEEDOT, SPECIES_PICHU},              // 5
        {SPECIES_WEEDLE, SPECIES_CHIKORITA, SPECIES_GEODUDE},           // 6
        {SPECIES_PIDGEY, SPECIES_MANKEY, SPECIES_LARVITAR},             // 7
        {SPECIES_CATERPIE, SPECIES_LOTAD, SPECIES_MAGBY},               // 8
        {SPECIES_PIDGEY, SPECIES_SEEDOT, SPECIES_PICHU},                // 9
        {SPECIES_POLIWAG, SPECIES_LARVITAR, SPECIES_PICHU},             // 10
        {SPECIES_PIDGEY, SPECIES_NIDORAN_F, SPECIES_PICHU},             // 11
        {SPECIES_NIDORAN_M, SPECIES_GEODUDE_ALOLAN, SPECIES_ZUBAT},     // 12
        {SPECIES_NIDORAN_F, SPECIES_CLEFFA, SPECIES_BAGON},             // 13
        {SPECIES_ODDISH, SPECIES_POLIWAG, SPECIES_MAGBY},               // 14
        {SPECIES_CLEFFA, SPECIES_MACHOP, SPECIES_ARON},                 // 15
        {SPECIES_IGGLYBUFF, SPECIES_ZIGZAGOON_GALARIAN, SPECIES_GASTLY}, // 16
        {SPECIES_PICHU, SPECIES_POLIWAG, SPECIES_TEDDIURSA},            // 17
        {SPECIES_ABRA, SPECIES_MACHOP, SPECIES_LARVITAR},               // 18
        {SPECIES_MACHOP, SPECIES_ZIGZAGOON_GALARIAN, SPECIES_GASTLY},   // 19
        {SPECIES_BELLSPROUT, SPECIES_AZURILL, SPECIES_DRATINI},         // 20
        {SPECIES_WEEDLE, SPECIES_SEEDOT, SPECIES_GEODUDE},              // 21
        {SPECIES_GASTLY, SPECIES_RALTS, SPECIES_HAPPINY},               // 22
        {SPECIES_DRATINI, SPECIES_TEDDIURSA, SPECIES_ARON},             // 23
        {SPECIES_RHYHORN, SPECIES_ZUBAT, SPECIES_CHIKORITA},            // 24
        {SPECIES_HOPPIP, SPECIES_TEDDIURSA, SPECIES_CYNDAQUIL},         // 25
        {SPECIES_ELEKID, SPECIES_TOTODILE, SPECIES_SWINUB},             // 26
        {SPECIES_ZUBAT, SPECIES_LOTAD, SPECIES_GEODUDE},                // 27
        {SPECIES_POLIWAG, SPECIES_NIDORAN_M, SPECIES_MAREEP},           // 28
        {SPECIES_AZURILL, SPECIES_LARVITAR, SPECIES_ZUBAT},             // 29
        {SPECIES_AZURILL, SPECIES_CATERPIE, SPECIES_WEEDLE},            // 30
        {SPECIES_HOPPIP, SPECIES_NIDORAN_F, SPECIES_ARON},              // 31
        {SPECIES_HORSEA, SPECIES_CYNDAQUIL, SPECIES_GEODUDE_ALOLAN},    // 32
        {SPECIES_HAPPINY, SPECIES_DUSKULL, SPECIES_MANKEY},             // 33
        {SPECIES_LARVITAR, SPECIES_TOGEPI, SPECIES_MACHOP},             // 34
        {SPECIES_CATERPIE, SPECIES_BELLSPROUT, SPECIES_IGGLYBUFF},      // 35
        {SPECIES_WEEDLE, SPECIES_LOTAD, SPECIES_SWINUB},                // 36
        {SPECIES_LOTAD, SPECIES_GEODUDE_ALOLAN, SPECIES_TOGEPI},        // 37
        {SPECIES_SEEDOT, SPECIES_MIME_JR, SPECIES_TOGEPI},              // 38
        {SPECIES_MACHOP, SPECIES_MAGNEMITE, SPECIES_RALTS},             // 39
        {SPECIES_SLAKOTH, SPECIES_DUSKULL, SPECIES_MANKEY},             // 40
        {SPECIES_WHISMUR, SPECIES_GASTLY, SPECIES_MACHOP},              // 41
        {SPECIES_ARON, SPECIES_RALTS, SPECIES_HORSEA},                  // 42
        {SPECIES_TRAPINCH, SPECIES_GEODUDE_ALOLAN, SPECIES_TOGEPI},     // 43
        {SPECIES_SPHEAL, SPECIES_RHYHORN, SPECIES_GEODUDE_ALOLAN},      // 44
        {SPECIES_SPHEAL, SPECIES_TRAPINCH, SPECIES_MAGNEMITE},          // 45
        {SPECIES_BAGON, SPECIES_MANKEY, SPECIES_LARVITAR},              // 46
        {SPECIES_TRAPINCH, SPECIES_BELDUM, SPECIES_TOGEPI},             // 47
        {SPECIES_CYNDAQUIL, SPECIES_BUDEW, SPECIES_AZURILL},            // 48
        {SPECIES_RHYHORN, SPECIES_MAGNEMITE, SPECIES_HOPPIP},           // 49
        {SPECIES_TEDDIURSA, SPECIES_MAGNEMITE, SPECIES_SQUIRTLE},       // 50
        {SPECIES_RHYHORN, SPECIES_ELEKID, SPECIES_TOTODILE},            // 51
        {SPECIES_NIDORAN_M, SPECIES_ELEKID, SPECIES_SPHEAL},            // 52
        {SPECIES_TRAPINCH, SPECIES_MAGBY, SPECIES_MIME_JR},             // 53
        {SPECIES_HORSEA, SPECIES_GEODUDE_ALOLAN, SPECIES_TOGEPI},       // 54
        {SPECIES_CHARMANDER, SPECIES_SWINUB, SPECIES_MAREEP},           // 55
        {SPECIES_PORYGON, SPECIES_DUSKULL, SPECIES_RALTS},              // 56
        {SPECIES_GEODUDE, SPECIES_CYNDAQUIL, SPECIES_RALTS},            // 57
        {SPECIES_MANKEY, SPECIES_ZIGZAGOON_GALARIAN, SPECIES_DUSKULL},  // 58
        {SPECIES_BELDUM, SPECIES_CLEFFA, SPECIES_ZIGZAGOON_GALARIAN},   // 59
        {SPECIES_NIDORAN_F, SPECIES_MAGNEMITE, SPECIES_MIME_JR},        // 60
        {SPECIES_ELEKID, SPECIES_MAGBY, SPECIES_SWINUB},                // 61
        {SPECIES_PORYGON, SPECIES_SLAKOTH, SPECIES_HAPPINY},            // 62
        {SPECIES_RALTS, SPECIES_TRAPINCH, SPECIES_BELDUM}               // 63
};

extern const u16 gBirchBagGrass_Pal[];
extern const u32 gBirchBagTilemap[];
extern const u32 gBirchGrassTilemap[];
extern const u32 gBirchBagGrass_Gfx[];
extern const u32 gPokeballSelection_Gfx[];

u16 GetStarterPokemon(u16 chosenStarterId);
u16 GetStarterPokemon2(u16 chosenStarterId);
void CB2_ChooseStarter(void);
void CB2_ChooseStarter2(void);

#endif // GUARD_STARTER_CHOOSE_H
